version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=redis:6379
      - REDIS_ENABLED=true
      - REDIS_DB=0
      - REDIS_EXPIRATION_SECONDS=86400
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - STORAGE_MODE=local
      - SERVER_DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
      - ./env.yaml:/app/env.yaml
    depends_on:
      - redis
    networks:
      - wiki-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - wiki-network

volumes:
  redis-data:

networks:
  wiki-network:
    driver: bridge 